---------------- Staging level   --------- DEMIPT2.<CODE>_STG_<TABLE_NAME>
create table DEMIPT2.RUSN_STG_CLIENTS (
CLIENT_ID      VARCHAR2(20 BYTE),
LAST_NAME   VARCHAR2(100 BYTE),
FIRST_NAME  VARCHAR2(100 BYTE),
PATRONYMIC VARCHAR2(100 BYTE),
DATE_OF_BIRTH DATE,
PASSPORT_NUM VARCHAR2(15 BYTE),
PASSPORT_VALID_TO DATE,
PHONE VARCHAR2(20 BYTE),
CREATE_DT DATE,
UPDATE_DT DATE);

create table DEMIPT2.RUSN_STG_ACCOUNTS (
ACCOUNT CHAR(20 BYTE),
VALID_TO DATE,
CLIENT VARCHAR2(20 BYTE),
CREATE_DT DATE,
UPDATE_DT DATE)
commit;

create table DEMIPT2.RUSN_STG_CARDS(
CARD_NUM CHAR(20 BYTE), 
ACCOUNT CHAR(20 BYTE),
CREATE_DT	DATE,
UPDATE_DT	DATE);


create table DEMIPT2.RUSN_STG_TERMINALS (
TERMINAL_ID char(5) primary key,
TERMINAL_TYPO char(3),
TERMINAL_CITY varchar(50),
TERMINAL_ADDRESS varchar(250)
);
alter table DEMIPT2.RUSN_STG_TERMINALS drop constraint SYS_C00106229;

commit;

create table DEMIPT2.RUSN_STG_PSSPRT_BLCKLST (
PASSPORT_NUM CHAR2(15 BYTE),
ENTRY_DT date
);

create table DEMIPT2.RUSN_STG_TRANSACTIONS(
TRANS_ID char(11),
TRANS_DATE DATE,
CARD_NUM CHAR(20 BYTE), 
OPER_TYPE CHAR(8),
amnt decimal (15,2) ,
oper_result char(7),
terminal char(5), 
FOREIGN KEY (terminal) references demipt2.RUSN_STG_TERMINALS  (TERMINAL_ID)
);
alter table DEMIPT2.RUSN_STG_TRANSACTIONS modify ( TRANS_DATE timestamp(0) );
alter table DEMIPT2.RUSN_STG_TRANSACTIONS drop constraint SYS_C00106608;

-- STAGING_DELETIONS
CREATE TABLE demipt2.RUSN_STG_CLIENTS_DEL (
CLIENT_ID VARCHAR2(20 BYTE),
upload_date date);

CREATE TABLE demipt2.RUSN_STG_ACCOUNTS_DEL (
ACCOUNT VARCHAR2(20 BYTE),
upload_date date);

CREATE TABLE demipt2.RUSN_STG_CARDS_DEL (
CARD_NUM VARCHAR2(20 BYTE),
upload_date date);
Commit;


---------------- Detailed level --------    DEMIPT2.<CODE>_DWH_DIM_<TABLE_NAME>_HIST
create table DEMIPT2.RUSN_DWH_DIM_CLIENTS_HIST (
CLIENT_ID VARCHAR2(20 BYTE) primary key
, FIRST_NAME VARCHAR2(100 BYTE)
, LAST_NAME VARCHAR2(100 BYTE)
, PATRONYMIC VARCHAR2(100 BYTE)
, DATE_OF_BIRTH date
, PASSPORT_NUM VARCHAR2(15 BYTE)
, PHONE VARCHAR2(20 BYTE)
, effective_from date
, effective_to date
, deleted_flg char(1)
);
alter table DEMIPT2.RUSN_DWH_DIM_CLIENTS_HIST drop constraint SYS_C00106238 ;
alter table DEMIPT2.RUSN_DWH_DIM_CLIENTS_HIST add  (PASSPORT_VALID_TO DATE);

create table DEMIPT2.RUSN_DWH_DIM_ACCOUNTS_HIST (
ACCOUNT_NUM CHAR(20 BYTE) primary key 
, VALID_TO date
, CLIENT VARCHAR2(20 BYTE) references DEMIPT2.RUSN_DWH_DIM_CLIENTS_HIST (CLIENT_ID)
, effective_from date
, effective_to date
, deleted_flg char(1)
);
alter table DEMIPT2.RUSN_DWH_DIM_ACCOUNTS_HIST drop constraint SYS_C00106239 ;
alter table DEMIPT2.RUSN_DWH_DIM_ACCOUNTS_HIST drop constraint SYS_C00106240 ;

create table DEMIPT2.RUSN_DWH_DIM_CARDS_HIST(
CARD_NUM CHAR(20 BYTE) primary key
, ACCOUNT_NUM CHAR(20 BYTE) references DEMIPT2.RUSN_DWH_DIM_ACCOUNTS_HIST (ACCOUNT_NUM)
, effective_from date
, effective_to date
, deleted_flg char(1)
);
alter table DEMIPT2.RUSN_DWH_DIM_CARDS_HIST drop constraint SYS_C00106241 ;
alter table DEMIPT2.RUSN_DWH_DIM_CARDS_HIST drop constraint SYS_C00106242 ;

create table DEMIPT2.RUSN_DWH_DIM_TERMINALS_HIST (
TERMINAL_ID char(5) primary key
, TERMINAL_TYPO char(3)
, TERMINAL_CITY varchar(50)
, TERMINAL_ADDRESS varchar(250)
, effective_from date
, effective_to date
, deleted_flg char(1)
);
alter table DEMIPT2.RUSN_DWH_FACT_TRANSACTIONS drop constraint SYS_C00106243;
commit;

---------------- Transactional Tables  DEMIPT2.<CODE>_DWH_FACT_<TABLE_NAME>
create table DEMIPT2.RUSN_DWH_FACT_TRANSACTIONS(
TRANS_ID char(11),
TRANS_DATE DATE,
CARD_NUM CHAR(20 BYTE), 
OPER_TYPE CHAR(8),
amnt decimal (15,2) ,
oper_result char(7),
terminal char(5), 
FOREIGN KEY (terminal) references demipt2.RUSN_DWH_DIM_TERMINALS_HIST (TERMINAL_ID),
FOREIGN KEY  (CARD_NUM) references DEMIPT2.RUSN_DWH_DIM_CARDS_HIST (CARD_NUM)
);
alter table DEMIPT2.RUSN_DWH_FACT_TRANSACTIONS modify ( TRANS_DATE timestamp);
alter table DEMIPT2.RUSN_DWH_FACT_TRANSACTIONS drop constraint SYS_C00106246;
alter table DEMIPT2.RUSN_DWH_FACT_TRANSACTIONS drop constraint SYS_C00106247;

create table DEMIPT2.RUSN_DWH_FACT_PSSPRT_BLCKLST (
PASSPORT_NUM VARCHAR2(15 BYTE),
ENTRY_DT date
);
commit;

------------MetaData table DEMIPT2.<CODE>_META_<TABLE_NAME>
INSERT INTO "DEMIPT2"."RUSN_META" (TABLE_DB, TABLE_NAME, LAST_UPDATE) VALUES ('DEMIPT2', 'BANK.CLIENTS', TO_DATE('1899-01-01', 'YYYY-MM-DD'));
INSERT INTO "DEMIPT2"."RUSN_META" (TABLE_DB, TABLE_NAME, LAST_UPDATE) VALUES ('DEMIPT2', 'BANK.ACCOUNTS', TO_DATE('1899-01-01', 'YYYY-MM-DD'));
INSERT INTO "DEMIPT2"."RUSN_META" (TABLE_DB, TABLE_NAME, LAST_UPDATE) VALUES ('DEMIPT2', 'BANK.CARDS', TO_DATE('1899-01-01', 'YYYY-MM-DD'));
INSERT INTO "DEMIPT2"."RUSN_META" (TABLE_DB, TABLE_NAME, LAST_UPDATE) VALUES ('FILE', 'TERNIMALS', TO_DATE('1899-01-01', 'YYYY-MM-DD'));
INSERT INTO "DEMIPT2"."RUSN_META" (TABLE_DB, TABLE_NAME, LAST_UPDATE) VALUES ('FILE', 'TRANSACTIONS', TO_DATE('1899-01-01', 'YYYY-MM-DD'));
INSERT INTO "DEMIPT2"."RUSN_META" (TABLE_DB, TABLE_NAME, LAST_UPDATE) VALUES ('FILE', 'BLCK_PASSP', TO_DATE('1899-01-01', 'YYYY-MM-DD'))

--report table DEMIPT2.<CODE>_REP_FRAUD
create table DEMIPT2.RUSN_REP_FRAUD
(event_dt date,
PASSPORT VARCHAR2(15 BYTE),
FIO VARCHAR2(300 BYTE),
EVENT_TYPE VARCHAR2(45 BYTE),
REPORT_DT date);
alter table RUSN_REP_FRAUD add PHONE CHAR(8);
alter table RUSN_REP_FRAUD modify PHONE CHAR(16);
commit;
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++